"""Every kind of banner a rally can be raised on, as the GAME names them (#1317).
The player asked for the whole list — «кроме Роковой Элиты есть ещё генералы, простые и
элитные» — so it was read rather than guessed: `lw_world_monster` in the live client, every
row carrying `boss = 1`, grouped by the `name` key it points at. Seventy-one name keys, and
the game gives several of them the SAME words (six different rows are all «Роковая Элита»),
so the kinds below are the game's own NAMES with the keys that map onto each.

**Nothing here is translated by hand.** The label of every kind is `rally_limit.type.<kind>`
in `panel/locales/`, filled from the game's own tables with `tools/game_locale.py`; this
module only says which config key is which kind.

Two kinds are not species at all and are matched off their own managers by the press:
`alliance_drill` (`AllyDrillDataManager.actInfo.data.bossUuid`) and `zombie_invasion` (the
invasion's own monster lists). `monster` is the fallback for a banner nothing could name.
"""
from __future__ import annotations

#: The fallback: a banner whose species the config could not name.
FALLBACK_KIND = "monster"

#: The two events, matched by their own managers rather than by a species.
EVENT_KINDS = ("alliance_drill", "zombie_invasion")

#: `name key in lw_world_monster` -> the kind it belongs to.
KIND_OF_NAME: dict = {
    "season_s4_monster_bossname_xueye": "blood_night_doom_elite",
    "season_s4_monster_blood_patrol_name": "blood_night_oni_legion",
    "season_s4_monster_840320_name": "bloodnight_alpha_wolf",
    "activity_violet_003": "cl_7_victim",
    "season_monster_name003": "corruptor_butcher",
    "season_monster_name002": "corruptor_guard",
    "season_monster_name004": "corruptor_gunner",
    "season_monster_name201900": "crimson_butcher",
    "season_s1_boss_name_tanke": "crimson_colossus",
    "season_s1_boss_name_feiji": "crimson_doctor",
    "season_monster_name20110000": "crimson_guard",
    "season_monster_name201800": "crimson_gunner",
    "activity_name_1000016": "crimson_legion",
    "season_s1_boss_name_daodan": "crimson_lycan",
    "season_s3_dark_knight_name": "desert_boss",
    "300602": "doom_elite",
    "s6_monster_eliteboss_name": "doom_elite",
    "season_monster_name001": "doom_elite",
    "season_s2_monster_name001": "doom_elite",
    "season_s3_monster_name007": "doom_elite",
    "season_s4_monster_lang_name": "doom_elite",
    "monster_boss_name_001": "doom_walker",
    "monica_event_des004": "fugitive_insurgents",
    "2010220": "general_trial",
    "challenge_zombie_001": "general_trial_elite",
    "2010221": "general_trial_forces",
    "s6_monster_crocodile_name": "giant_crocodile",
    "season6_piranha_monster_name": "giant_devouring_flower",
    "season_s2_activity_1000047_description_19": "giant_glacieradon",
    "season_s3_monster_name04": "giant_sandworm",
    "mail_godzilla_name": "glacieradon",
    "season_s3_monster_name010": "golden_annihilator",
    "season_s3_monster_name008": "golden_defender",
    "season_s3_monster_name009": "golden_striker",
    "2901011": "invading_zombies",
    "monstername_redmason": "ironclad_vehicle",
    "season_s3_monster_name03": "large_sandworm",
    "2010115": "maxwell_s_comrades",
    "alliance_government_skill_goddess_3": "mummies_summoned_by_0",
    "season_name_jushou": "mutant_beast",
    "season_s2_monster_name014": "mutant_gorilla",
    "monster_name_zombierush_eliteBoss_bus_alter": "mutant_raider",
    "season_s2_monster_name004": "mutated_bear",
    "season_s2_monster_name002": "mutated_mammoth",
    "season_s6_government_skill_desc74": "night_army",
    "season_s4_monster_jiutun_name": "oni_d_ji",
    "season_s4_city_boss_name": "oni_general",
    "season_s4_monster_wushi_name": "oni_samurai",
    "season_s4_monster_tiangou_name": "oni_tengu",
    "s5_monster_feiji_boss_name": "plague_marauder",
    "monster_youdang_s5_name": "plague_nomad",
    "s5_monster_tanke_boss_name": "plague_ravager",
    "s5_monster_daodan_boss_name": "plague_ringmaster",
    "activity_Lambo_008": "rainforest_poachers",
    "activity_Sara_008": "renegade_oninjas",
    "s6_monster_boss_feiji_name": "shadow_colossus",
    "s6_monster_boss_wonder_name": "shadow_destroyer",
    "s6_monster_boss_daodan_name": "shadow_fighter",
    "s6_monster_boss_tanke_name": "shadow_guard",
    "mail_airship_monster_name": "sky_predator",
    "mail_challenge_zombie_monster_name": "sky_predator",
    "season_s3_monster_name02": "small_sandworm",
    "activity_Scarlett_008": "treasure_smuggler",
    "season_s3_monster_name011": "wandering_mummy_warlord",
    "season_s4_monster_patrol_name": "wandering_oni_legion",
    "season_s4_blood_boss_name": "wandering_oniwagon",
    "activity_Vinom_008": "wasteland_outlaws",
    "running_boss_willy_name": "willson_the_slugger",
    "2901012": "zombie_boss",
    "monster_name_1040000": "zombie_horde",
    "monster_name_zombierush_eliteBoss_bus": "zombie_raider",
}

#: Every kind, in the order the panel draws them: the fallback, then the
#: two events, then the species by their English name.
KIND_ORDER: tuple = (
    "monster",
    "alliance_drill",
    "zombie_invasion",
    "blood_night_doom_elite",
    "blood_night_oni_legion",
    "bloodnight_alpha_wolf",
    "cl_7_victim",
    "corruptor_butcher",
    "corruptor_guard",
    "corruptor_gunner",
    "crimson_butcher",
    "crimson_colossus",
    "crimson_doctor",
    "crimson_guard",
    "crimson_gunner",
    "crimson_legion",
    "crimson_lycan",
    "desert_boss",
    "doom_elite",
    "doom_walker",
    "fugitive_insurgents",
    "general_trial",
    "general_trial_elite",
    "general_trial_forces",
    "giant_crocodile",
    "giant_devouring_flower",
    "giant_glacieradon",
    "giant_sandworm",
    "glacieradon",
    "golden_annihilator",
    "golden_defender",
    "golden_striker",
    "invading_zombies",
    "ironclad_vehicle",
    "large_sandworm",
    "maxwell_s_comrades",
    "mummies_summoned_by_0",
    "mutant_beast",
    "mutant_gorilla",
    "mutant_raider",
    "mutated_bear",
    "mutated_mammoth",
    "night_army",
    "oni_d_ji",
    "oni_general",
    "oni_samurai",
    "oni_tengu",
    "plague_marauder",
    "plague_nomad",
    "plague_ravager",
    "plague_ringmaster",
    "rainforest_poachers",
    "renegade_oninjas",
    "shadow_colossus",
    "shadow_destroyer",
    "shadow_fighter",
    "shadow_guard",
    "sky_predator",
    "small_sandworm",
    "treasure_smuggler",
    "wandering_mummy_warlord",
    "wandering_oni_legion",
    "wandering_oniwagon",
    "wasteland_outlaws",
    "willson_the_slugger",
    "zombie_boss",
    "zombie_horde",
    "zombie_raider",
)
