"""The little HTTP server the phone talks to.

Deliberately the standard library and nothing else. The panel installs on other people's
Windows machines out of a `.bat` file, and a remote control that needed a web framework
would be a dependency, a virtualenv and a support question — `http.server` on a thread
is a hundred lines and cannot go out of date.

WHAT IT SERVES. Two things, and it keeps them apart: the PAGE (the files in `static/`,
which are the same for everybody and say nothing about this account) and the API
(`panel/web/api.py`, which is this profile's live state and its buttons). The page is
open, the API needs the token — because the page is useless without one and refusing it
too would only mean a blank screen instead of a login box.

THE TOKEN. One string per profile, generated by the panel and shown on its «Веб» tab.
It travels either as a cookie (set once, by the login box) or as `?token=…` on the URL,
which is what makes the link the tab shows work in one tap from a phone. Compared with
`hmac.compare_digest`, so the comparison does not leak how much of it was right.

THIS IS NOT AN INTERNET SERVER. It is meant for the phone in the same flat as the
machine that farms — a home network, behind a router that forwards nothing. It has no
TLS, and a token in a URL is a token in a browser history; anyone who wants it reachable
from outside should put it behind something that does TLS properly rather than open the
port. The tab says as much, in every locale.
"""
from __future__ import annotations

import hmac
import json
import mimetypes
import os
import socket
import threading
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# FIRST, and for its side effect: it is what puts the repository's `tools/lib` on the
# path, so `game_paths` below resolves whichever way this module was reached.
from ..runtime import paths as _paths  # noqa: F401

import game_paths                      # noqa: E402  (needs the bootstrap above)

from .api import WebApi, static_dir    # noqa: E402


def default_port() -> int:
    """The port to listen on when the profile has not named one.

    Asked of `tools/lib/game_paths.py` and never spelled here: `LW_WEB_PORT` is the
    machine's answer, 9761 is everybody's, and the profile's own knob beats both
    (`CLAUDE.md`, «Nothing about one machine is written into the code»). A function
    rather than a constant, so a variable set after this module was imported still
    counts — the panel imports early and is configured late.
    """
    return game_paths.web_port()

#: Every interface by default: the point of it is a DIFFERENT machine reaching this one,
#: so `127.0.0.1` would be a remote control that only works where nobody needs it. A
#: profile that wants it local-only sets the host knob to `127.0.0.1`.
DEFAULT_HOST = "0.0.0.0"

#: The cookie the login box sets. Session-scoped: closing the browser forgets it, which
#: is the right default for a phone that leaves the flat.
COOKIE = "lwvp_web"

#: The biggest body a request may carry. Every POST here is `{"name": "...", …}`.
MAX_BODY = 64 * 1024

#: The routes that answer without a token. `ping` is how the page asks whether it has
#: one; `i18n` is the locale table, which is the same eleven files the repository ships
#: in the open and says nothing whatever about this account — and without it the login
#: box would be the one screen in the panel written in locale keys.
PUBLIC = frozenset({"/api/i18n"})

#: WHO IS SERVING, in THIS process: `port -> WebServer`.
#:
#: One server per window, not per profile. The API answers for every open profile
#: (`panel/web/api.py`), so a second session starting a second socket would be two
#: addresses showing the same two accounts — and the second one would fail to bind
#: anyway, which reads as a fault rather than as "already done". A session whose switch
#: is on and whose port is held by a sibling shows the address that IS serving instead
#: (`panel/tabs/web.py`).
#:
#: Process-wide on purpose: a SECOND PANEL is a second process and gets its own
#: registry, so it binds — or fails on the port, which is then a real clash and is said
#: out loud.
_SERVING: dict = {}
_SERVING_LOCK = threading.Lock()


def serving(port: int):
    """The server holding ``port`` in this process, or ``None``."""
    with _SERVING_LOCK:
        return _SERVING.get(int(port))


def serving_any():
    """Any server this window is running — what a tab shows when a sibling holds it."""
    with _SERVING_LOCK:
        return next(iter(_SERVING.values()), None)


class WebServer:
    """One profile's remote control: a thread, a socket, and the API behind it."""

    def __init__(self, rt, *, host: str = DEFAULT_HOST, port: int | None = None,
                 token: str = "", api: "WebApi | None" = None) -> None:
        self.rt = rt
        self.host = host or DEFAULT_HOST
        # `None` is «whatever this machine says» — not 9761, which would be this file
        # spelling the number a second time. `0` is kept as itself: the tests bind an
        # ephemeral port with it.
        self.port = default_port() if port is None else int(port)
        self.token = str(token or "")
        self.api = api if api is not None else WebApi(rt)
        #: Which profile started it. Shown by a sibling session's tab, which has to be
        #: able to say WHOSE window is answering on that address.
        self.owner = str(getattr(getattr(rt, "profiles", None), "active", "") or "")
        self._httpd = None
        self._thread = None

    # -- lifecycle ----------------------------------------------------------
    @property
    def running(self) -> bool:
        return self._httpd is not None

    def start(self) -> None:
        """Bind and serve. Raises `OSError` when the port is taken — the caller says so.

        A taken port is the ordinary failure here (the other profile is on it, or an
        earlier panel has not let go yet), so it travels as the exception it is rather
        than as a `False` the caller may forget to look at.
        """
        if self.running:
            return
        if not self.token:
            raise ValueError("web server started without a token")
        self.api.attach()
        handler = _make_handler(self)
        try:
            httpd = ThreadingHTTPServer((self.host, self.port), handler)
        except OSError:
            self.api.detach()
            raise
        httpd.daemon_threads = True
        self._httpd = httpd
        with _SERVING_LOCK:
            _SERVING[self.bound_port()] = self
        self._thread = threading.Thread(target=httpd.serve_forever, kwargs={"poll_interval": 0.5},
                                        daemon=True, name="panel-web")
        self._thread.start()

    def stop(self) -> None:
        """Let the port go. Safe to call on a server that never started."""
        httpd, self._httpd = self._httpd, None
        thread, self._thread = self._thread, None
        self.api.detach()
        with _SERVING_LOCK:
            for port, server in list(_SERVING.items()):
                if server is self:
                    del _SERVING[port]
        if httpd is None:
            return
        try:
            httpd.shutdown()
        except Exception:                   # noqa: BLE001 — closing, never the panel
            pass
        try:
            httpd.server_close()
        except Exception:                   # noqa: BLE001
            pass
        if thread is not None:
            thread.join(timeout=3.0)

    def bound_port(self) -> int:
        """The port actually listening — which is not the asked-for one when it was 0."""
        if self._httpd is None:
            return self.port
        return int(self._httpd.server_address[1])

    # -- authentication ------------------------------------------------------
    def accepts(self, presented: str) -> bool:
        return bool(presented) and hmac.compare_digest(str(presented), self.token)


def addresses() -> list:
    """The addresses this machine can be reached at, best guess first.

    Asked of the operating system rather than configured: which network card the phone
    is on is not something a repository may know, and a machine with two of them has two
    right answers. The loopback one is always last — it is the one that cannot possibly
    work from a phone, and it is the one a machine with no network at all is left with.
    """
    out: list = []
    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            # Nothing is sent: connecting a UDP socket only picks the route, which is
            # how the OS is asked «which of my addresses would you use to leave here».
            probe.connect(("192.0.2.1", 9))     # TEST-NET-1 (RFC 5737): routed nowhere
            out.append(probe.getsockname()[0])
        finally:
            probe.close()
    except OSError:
        pass
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            address = info[4][0]
            if address not in out and not address.startswith("127."):
                out.append(address)
    except OSError:
        pass
    out.append("127.0.0.1")
    return out


def _make_handler(server: WebServer):
    """The request handler class, closed over the one server it belongs to."""

    class Handler(BaseHTTPRequestHandler):
        server_version = "LastWarPanel"
        sys_version = ""
        protocol_version = "HTTP/1.1"

        # -- the two verbs --------------------------------------------------
        def do_GET(self) -> None:               # noqa: N802 — BaseHTTPRequestHandler
            path, query = _split(self.path)
            if path.startswith("/api/"):
                self._api("GET", path, query, {})
                return
            self._page(path, query)

        def do_POST(self) -> None:              # noqa: N802
            path, query = _split(self.path)
            body = self._body()
            if path == "/api/login":
                self._login(body)
                return
            if path.startswith("/api/"):
                self._api("POST", path, query, body)
                return
            self._send(404, b"", "text/plain")

        # -- the API --------------------------------------------------------
        def _api(self, method: str, path: str, query: dict, body: dict) -> None:
            if path == "/api/ping":
                self._json(200, {"ok": True, "authorised": self._authorised(query)})
                return
            if not self._authorised(query) and path not in PUBLIC:
                self._json(401, {"error": "unauthorised"})
                return
            try:
                status, payload = server.api.dispatch(method, path, query, body)
            except Exception as exc:            # noqa: BLE001 — one request, not the panel
                server.rt.log.put(f"[web] {path}: {exc}")
                self._json(500, {"error": str(exc)})
                return
            self._json(status, payload)

        def _login(self, body: dict) -> None:
            presented = str(body.get("token") or "")
            if not server.accepts(presented):
                server.rt.say("web", "web.log.refused", peer=self.client_address[0])
                self._json(403, {"error": "bad_token"})
                return
            self._json(200, {"ok": True},
                       headers=[("Set-Cookie", f"{COOKIE}={presented}; Path=/; "
                                               "SameSite=Lax; HttpOnly")])

        # -- the page -------------------------------------------------------
        def _page(self, path: str, query: dict) -> None:
            """Serve one file out of `static/`. A token on the URL is remembered here.

            Landing with `?token=…` sets the cookie and redirects to the bare path, so
            the address bar (and the history behind it) does not keep the token, and a
            reload works without it.
            """
            token = _one(query.get("token"))
            if token and server.accepts(token):
                self._send(303, b"", "text/plain", headers=[
                    ("Location", path or "/"),
                    ("Set-Cookie", f"{COOKIE}={token}; Path=/; SameSite=Lax; HttpOnly")])
                return
            name = "index.html" if path in ("", "/") else path.lstrip("/")
            root = static_dir()
            full = os.path.normpath(os.path.join(root, name))
            if not full.startswith(root) or not os.path.isfile(full):
                self._send(404, b"", "text/plain")
                return
            try:
                with open(full, "rb") as fh:
                    blob = fh.read()
            except OSError:
                self._send(404, b"", "text/plain")
                return
            kind = mimetypes.guess_type(full)[0] or "application/octet-stream"
            self._send(200, blob, kind,
                       headers=[("Cache-Control", "no-cache")])

        # -- plumbing -------------------------------------------------------
        def _authorised(self, query: dict) -> bool:
            for presented in (self.headers.get("X-Panel-Token", ""),
                              _cookie(self.headers.get("Cookie", "")),
                              _one(query.get("token"))):
                if server.accepts(presented):
                    return True
            return False

        def _body(self) -> dict:
            try:
                length = int(self.headers.get("Content-Length") or 0)
            except ValueError:
                return {}
            if length <= 0 or length > MAX_BODY:
                return {}
            try:
                raw = self.rfile.read(length)
                data = json.loads(raw.decode("utf-8"))
            except Exception:                   # noqa: BLE001 — a bad body is an empty one
                return {}
            return data if isinstance(data, dict) else {}

        def _json(self, status: int, payload: dict, headers=None) -> None:
            blob = json.dumps(payload, ensure_ascii=False).encode("utf-8")
            self._send(status, blob, "application/json; charset=utf-8", headers)

        def _send(self, status: int, blob: bytes, kind: str, headers=None) -> None:
            try:
                self.send_response(status)
                self.send_header("Content-Type", kind)
                self.send_header("Content-Length", str(len(blob)))
                for key, value in headers or ():
                    self.send_header(key, value)
                self.end_headers()
                if blob:
                    self.wfile.write(blob)
            except (BrokenPipeError, ConnectionResetError):
                pass                            # the phone walked out of range

        def log_message(self, fmt: str, *args) -> None:
            """Into the panel's debug log, never onto a console that may not exist.

            The default writes to stderr, and a windowed build (`pythonw`) has none —
            which on Windows is not "no output" but an exception on the first request.
            """
            try:
                server.rt.dbg("web").debug(fmt, *args)
            except Exception:                   # noqa: BLE001 — logging, never the server
                pass

    return Handler


def _split(raw: str) -> tuple:
    """``(path, query)`` — the query FLATTENED to one value per name.

    `parse_qs` hands back a list per name, and every reader downstream wants the value:
    `since=[「12」]` read as a number is not 12, it is the fallback, silently — which is a
    log that re-sends its whole tail on every poll and nobody the wiser.
    """
    parsed = urllib.parse.urlsplit(raw)
    return parsed.path, {key: values[0] if values else ""
                         for key, values in urllib.parse.parse_qs(parsed.query).items()}


def _one(value) -> str:
    """One query parameter, whether it arrived as a list or already flattened."""
    if isinstance(value, (list, tuple)):
        return str(value[0]) if value else ""
    return str(value or "")


def _cookie(header: str) -> str:
    for part in (header or "").split(";"):
        key, _, value = part.strip().partition("=")
        if key == COOKIE:
            return value
    return ""
