"""The little HTTP server the phone talks to.

Deliberately the standard library and nothing else. The panel installs on other people's
Windows machines out of a `.bat` file, and a remote control that needed a web framework
would be a dependency, a virtualenv and a support question — `http.server` on a thread
is a hundred lines and cannot go out of date.

WHAT IT SERVES. Two things, and it keeps them apart: the PAGE (the files in `static/`,
which are the same for everybody and say nothing about this account) and the API
(`panel/web/api.py`, which is this profile's live state and its buttons). The page is
open, the API needs the token — because the page is useless without one and refusing it
too would only mean a blank screen instead of a login box.

THE TOKEN. One string per WINDOW, generated by the panel and shown in menu → «Веб»
(`panel/runtime/web_control.py`). It travels either as a cookie (set once, by the login
box) or as `?token=…` on the URL, which is what makes the link beside the switch work in
one tap from a phone. Compared with `hmac.compare_digest`, so the comparison does not
leak how much of it was right.

REACHING IT FROM OUTSIDE is the router's business: this listens on every interface, so
a forwarded port is all it takes, and who may connect is the filter on the router. The
traffic is plain HTTP unless a certificate is named in that dialog — a token in a URL is a
token in a browser history and in every hop along the way — so the guessing is bounded
here instead: wrong tokens are counted per address and a sign-in from a new one is said
out loud in the log.
"""
from __future__ import annotations

import hmac
import json
import mimetypes
import os
import socket
import socketserver
import ssl
import threading
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# FIRST, and for its side effect: it is what puts the repository's `tools/lib` on the
# path, so `game_paths` below resolves whichever way this module was reached.
from ..runtime import paths as _paths  # noqa: F401
from .. import debug_log

import game_paths                      # noqa: E402  (needs the bootstrap above)

from .api import WebApi, static_dir    # noqa: E402


def default_port() -> int:
    """The port to listen on when the profile has not named one.

    Asked of `tools/lib/game_paths.py` and never spelled here: `LW_WEB_PORT` is the
    machine's answer, 9761 is everybody's, and the profile's own knob beats both
    (`CLAUDE.md`, «Nothing about one machine is written into the code»). A function
    rather than a constant, so a variable set after this module was imported still
    counts — the panel imports early and is configured late.
    """
    return game_paths.web_port()

#: Every interface by default: the point of it is a DIFFERENT machine reaching this one,
#: so `127.0.0.1` would be a remote control that only works where nobody needs it. A
#: profile that wants it local-only sets the host knob to `127.0.0.1`.
DEFAULT_HOST = "0.0.0.0"

#: The cookie the login box sets.
COOKIE = "lwvp_web"

#: How long a signed-in browser stays signed in. A session cookie (forgotten when the
#: browser closes) was the right answer while this only ever answered on the home
#: network; behind a forwarded port the cookie IS the token, on a phone that may be
#: lost, so it expires on its own. A week is long enough that nobody re-types the token
#: every day and short enough that a phone left behind stops being a key.
COOKIE_MAX_AGE_SEC = 7 * 24 * 3600

#: HOW MANY WRONG TOKENS an address may present before it is shut out, and for how long.
#: The token is 72 bits of randomness, so this is not what makes guessing hopeless — it
#: is what stops a machine on the open internet from trying at all, and what makes the
#: attempt visible in the log instead of drowning it.
MAX_ATTEMPTS = 6
LOCKOUT_SEC = 300.0

#: The biggest body a request may carry. Every POST here is `{"name": "...", …}`.
MAX_BODY = 64 * 1024

#: The routes that answer without a token. `ping` is how the page asks whether it has
#: one; `i18n` is the locale table, which is the same eleven files the repository ships
#: in the open and says nothing whatever about this account — and without it the login
#: box would be the one screen in the panel written in locale keys.
PUBLIC = frozenset({"/api/i18n"})

#: WHO IS SERVING, in THIS process: `port -> WebServer`.
#:
#: One server per window, not per profile. The API answers for every open profile
#: (`panel/web/api.py`), so a second session starting a second socket would be two
#: addresses showing the same two accounts — and the second one would fail to bind
#: anyway, which reads as a fault rather than as "already done". Since #1313 there is no
#: way for a window to ask for a second one at all: the switch, the port and the token
#: are one panel-wide block (`panel/runtime/web_control.py`), not a knob per profile.
#:
#: Process-wide on purpose: a SECOND PANEL is a second process and gets its own
#: registry, so it binds — or fails on the port, which is then a real clash and is said
#: out loud.
_SERVING: dict = {}
_SERVING_LOCK = threading.Lock()


def serving(port: int):
    """The server holding ``port`` in this process, or ``None``."""
    with _SERVING_LOCK:
        return _SERVING.get(int(port))


def serving_any():
    """Any server this window is running — what a tab shows when a sibling holds it."""
    with _SERVING_LOCK:
        return next(iter(_SERVING.values()), None)


class Attempts:
    """Wrong tokens, per address — the thing that makes an open address survivable.

    Deliberately tiny: a count and a time per peer, forgotten when it succeeds and
    forgotten wholesale when the map grows past a sane size (an address is four dozen
    bytes and nobody is going to fill memory with them faster than the panel restarts).
    """

    def __init__(self, limit: int = MAX_ATTEMPTS, lockout: float = LOCKOUT_SEC) -> None:
        self.limit, self.lockout = int(limit), float(lockout)
        self._by_peer: dict = {}
        self._lock = threading.Lock()

    def locked(self, peer: str, now: float | None = None) -> float:
        """Seconds this peer is still shut out for; ``0`` when it may try."""
        now = time.time() if now is None else now
        with self._lock:
            count, when = self._by_peer.get(peer, (0, 0.0))
        if count < self.limit:
            return 0.0
        left = self.lockout - (now - when)
        return left if left > 0 else 0.0

    def failed(self, peer: str, now: float | None = None) -> int:
        """Record a wrong token. Returns how many this peer has now made."""
        now = time.time() if now is None else now
        with self._lock:
            count, when = self._by_peer.get(peer, (0, 0.0))
            # A lockout that has run out starts the count again rather than leaving the
            # peer one attempt away from another one for ever.
            if count >= self.limit and now - when >= self.lockout:
                count = 0
            count += 1
            if len(self._by_peer) > 4096:
                self._by_peer.clear()
            self._by_peer[peer] = (count, now)
            return count

    def passed(self, peer: str) -> None:
        with self._lock:
            self._by_peer.pop(peer, None)


class _Server(ThreadingHTTPServer):
    """`ThreadingHTTPServer` that does not look its own name up in DNS (#1226).

    `HTTPServer.server_bind` ends with `self.server_name = socket.getfqdn(host)`, and on
    the wildcard address that is a **reverse DNS lookup for `0.0.0.0`**: measured on this
    machine, 832–1004 ms, inside the constructor, on whatever thread called it. The tab
    calls it from `ensure_loaded` — which is the Tk thread — so switching the web server
    on, or merely opening a panel with it already on, froze the window for a second.

    `server_name` is only ever used to fill in a `Host:` the client did not send. Nothing
    here reads it: every response is built from the request, and the address a person is
    given is printed by the tab from the port. So the lookup buys nothing at all, and
    `gethostname()` — which is free, and is what the lookup starts from — is a better
    answer than a reverse lookup of a wildcard.
    """

    def server_bind(self) -> None:
        # `socketserver.TCPServer`'s half (bind + getsockname), named OUTRIGHT. Not
        # `super(ThreadingHTTPServer, self)`, which walks on to `HTTPServer.server_bind`
        # — the very method whose last line is the lookup — and skips nothing at all.
        socketserver.TCPServer.server_bind(self)
        host, port = self.server_address[:2]
        try:
            self.server_name = socket.gethostname()
        except OSError:                      # a machine that will not say; it is a label
            self.server_name = str(host)
        self.server_port = port


class WebServer:
    """One window's remote control: a thread, a socket, and the API behind it."""

    def __init__(self, rt, *, host: str = DEFAULT_HOST, port: int | None = None,
                 token: str = "", api: "WebApi | None" = None,
                 certfile: str = "", keyfile: str = "") -> None:
        self.rt = rt
        self.host = host or DEFAULT_HOST
        # `None` is «whatever this machine says» — not 9761, which would be this file
        # spelling the number a second time. `0` is kept as itself: the tests bind an
        # ephemeral port with it.
        self.port = default_port() if port is None else int(port)
        self.token = str(token or "")
        # OPTIONAL TLS, and the person's own certificate. The panel does not make one:
        # generating a certificate needs a library this project does not depend on, and
        # a self-signed one warns in the browser once per device anyway — so this is a
        # door for somebody who already has a certificate (or made one with `openssl`),
        # not a promise of encryption nobody asked for.
        self.certfile = str(certfile or "").strip()
        self.keyfile = str(keyfile or "").strip()
        self.api = api if api is not None else WebApi(rt)
        #: Which profile it was started FROM: the fallback for a request that names
        #: none, and where its own commentary is said. Re-pointed when that profile is
        #: closed (`panel/runtime/web_control.py::follow`).
        self.owner = str(getattr(getattr(rt, "profiles", None), "active", "") or "")
        #: Wrong tokens, per address (:class:`Attempts`).
        self.attempts = Attempts()
        #: Addresses that have signed in during this run, so the log says «somebody new
        #: came in» once rather than on every poll.
        self._seen: set = set()
        self._httpd = None
        self._thread = None

    # -- lifecycle ----------------------------------------------------------
    @property
    def running(self) -> bool:
        return self._httpd is not None

    @property
    def scheme(self) -> str:
        """`https` when a certificate was given, `http` otherwise.

        Read by `panel/runtime/web_control.py` to build the address: an `http://` link
        to a server that only speaks TLS fails in a way nobody diagnoses on a phone.
        """
        return "https" if self.certfile else "http"

    def start(self) -> None:
        """Bind and serve. Raises `OSError` when the port is taken — the caller says so.

        A taken port is the ordinary failure here (another program is on it, or an
        earlier panel has not let go yet), so it travels as the exception it is rather
        than as a `False` the caller may forget to look at.
        """
        if self.running:
            return
        if not self.token:
            raise ValueError("web server started without a token")
        self.api.attach()
        handler = _make_handler(self)
        try:
            httpd = _Server((self.host, self.port), handler)
        except OSError:
            self.api.detach()
            raise
        httpd.daemon_threads = True
        if self.certfile:
            # A certificate that cannot be loaded RAISES rather than falling back to
            # plain HTTP: believing you have TLS and not having it is the one failure
            # here worse than having none, and the caller says so in the dialog.
            try:
                context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
                context.load_cert_chain(self.certfile, self.keyfile or None)
                httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
            except Exception:
                httpd.server_close()
                self.api.detach()
                raise
        self._httpd = httpd
        with _SERVING_LOCK:
            _SERVING[self.bound_port()] = self
        self._thread = threading.Thread(target=httpd.serve_forever, kwargs={"poll_interval": 0.5},
                                        daemon=True, name="panel-web")
        self._thread.start()

    def stop(self) -> None:
        """Let the port go. Safe to call on a server that never started."""
        httpd, self._httpd = self._httpd, None
        thread, self._thread = self._thread, None
        self.api.detach()
        with _SERVING_LOCK:
            for port, server in list(_SERVING.items()):
                if server is self:
                    del _SERVING[port]
        if httpd is None:
            return
        try:
            httpd.shutdown()
        except Exception:                   # noqa: BLE001 — closing, never the panel
            pass
        try:
            httpd.server_close()
        except Exception:                   # noqa: BLE001
            pass
        if thread is not None:
            thread.join(timeout=3.0)

    def bound_port(self) -> int:
        """The port actually listening — which is not the asked-for one when it was 0."""
        if self._httpd is None:
            return self.port
        return int(self._httpd.server_address[1])

    # -- authentication ------------------------------------------------------
    def accepts(self, presented: str) -> bool:
        return bool(presented) and hmac.compare_digest(str(presented), self.token)


def addresses() -> list:
    """The addresses this machine can be reached at, best guess first.

    Asked of the operating system rather than configured: which network card the phone
    is on is not something a repository may know, and a machine with two of them has two
    right answers. The loopback one is always last — it is the one that cannot possibly
    work from a phone, and it is the one a machine with no network at all is left with.
    """
    out: list = []
    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            # Nothing is sent: connecting a UDP socket only picks the route, which is
            # how the OS is asked «which of my addresses would you use to leave here».
            probe.connect(("192.0.2.1", 9))     # TEST-NET-1 (RFC 5737): routed nowhere
            out.append(probe.getsockname()[0])
        finally:
            probe.close()
    except OSError:
        pass
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            address = info[4][0]
            if address not in out and not address.startswith("127."):
                out.append(address)
    except OSError:
        pass
    out.append("127.0.0.1")
    return out


def _make_handler(server: WebServer):
    """The request handler class, closed over the one server it belongs to."""

    class Handler(BaseHTTPRequestHandler):
        server_version = "LastWarPanel"
        sys_version = ""
        protocol_version = "HTTP/1.1"

        # -- the two verbs --------------------------------------------------
        def do_GET(self) -> None:               # noqa: N802 — BaseHTTPRequestHandler
            path, query = _split(self.path)
            # A PICTURE IS NOT JSON, and this is the only route that answers with one
            # (#1324). The «Ралли» screen draws the face of everybody standing in a
            # banner, out of the client's own cache; sending them inside the view would
            # be a megabyte per poll, so the view carries links and the browser fetches
            # each face once. Handled before `_api` because everything below there
            # encodes its answer as JSON.
            if path == "/api/avatar":
                self._avatar(query)
                return
            if path == "/api/itemicon":
                self._itemicon(query)
                return
            if path.startswith("/api/"):
                self._api("GET", path, query, {})
                return
            self._page(path, query)

        def do_POST(self) -> None:              # noqa: N802
            path, query = _split(self.path)
            body = self._body()
            if path == "/api/login":
                self._login(body)
                return
            if path.startswith("/api/"):
                self._api("POST", path, query, body)
                return
            self._send(404, b"", "text/plain")

        # -- the API --------------------------------------------------------
        def _api(self, method: str, path: str, query: dict, body: dict) -> None:
            if path == "/api/ping":
                self._json(200, {"ok": True, "authorised": self._authorised(query)})
                return
            if not self._authorised(query) and path not in PUBLIC:
                # A wrong token on an API route counts too, not only on the login form:
                # somebody guessing from outside has no reason to use the form at all.
                self._refuse(query)
                return
            try:
                status, payload = server.api.dispatch(method, path, query, body)
            except Exception as exc:            # noqa: BLE001 — one request, not the panel
                server.rt.log.put(f"[web] {path}: {exc}")
                self._json(500, {"error": str(exc)})
                return
            self._json(status, payload)

        # -- one picture ----------------------------------------------------
        def _avatar(self, query: dict) -> None:
            """Serve one face out of the shared avatar folder, by bare name (#1324).

            The folder is the MACHINE's and not an account's, by an explicit decision
            (`game_paths.avatar_cache()`, #1306): the same player has the same face
            whichever profile met them first. So this route takes no profile — there is
            nothing per-account to isolate here, and the name it is given is checked by
            `player_faces.file_named` rather than trusted.

            Behind the same token as everything else: a folder of players' photographs
            is not something to hand to whoever finds the port.
            """
            def resolve():
                import player_faces
                return player_faces.file_named(_one(query.get("face")))

            self._picture(query, resolve)

        def _itemicon(self, query: dict) -> None:
            """Serve one composed inventory cell out of `results/item_icons/cells`.

            The same shape as `_avatar` and for the same reasons (#1469): the pictures
            are the game's own art extracted onto THIS machine, they are identical for
            every profile, and the name is checked by `item_icons.file_named` rather
            than trusted. A cell that was never composed is a 404 and the phone simply
            shows the item's name — exactly what the window does with its glyph.
            """
            def resolve():
                import item_icons
                return item_icons.file_named(_one(query.get("cell")))

            self._picture(query, resolve)

        def _picture(self, query: dict, resolve) -> None:
            """The half both picture routes share: authorise, resolve, send, cache."""
            if not self._authorised(query):
                self._refuse(query)
                return
            try:
                full = resolve()
            except Exception:                   # noqa: BLE001 — one request, not the panel
                full = None
            if not full:
                self._send(404, b"", "text/plain")
                return
            try:
                with open(full, "rb") as fh:
                    blob = fh.read()
            except OSError:
                self._send(404, b"", "text/plain")
                return
            kind = "image/png" if full.lower().endswith(".png") else "image/jpeg"
            # Neither kind of picture changes under its own name while the panel is
            # open — a `picVer` bump writes a new face file, a re-composed cell a new
            # cell file — so the browser may keep it and stop asking.
            self._send(200, blob, kind,
                       headers=[("Cache-Control", "private, max-age=86400")])

        def _peer(self) -> str:
            """WHO is asking: the address the socket says, and nothing else.

            A forwarded port keeps it honest — a router rewrites the DESTINATION, not
            the source, so a visitor from the internet arrives with their own address
            and the lockout counts them as themselves. A proxy in front would break
            that, and the answer to a proxy is to trust the header it sets AND the
            socket it sets it from; there is no proxy here and there is not going to
            be one, so there is nothing to trust and nothing to spoof.
            """
            return self.client_address[0]

        def _login(self, body: dict) -> None:
            peer = self._peer()
            left = server.attempts.locked(peer)
            if left > 0:
                self._json(429, {"error": "too_many", "retry_after": int(left)},
                           headers=[("Retry-After", str(int(left)))])
                return
            presented = str(body.get("token") or "")
            if not server.accepts(presented):
                count = server.attempts.failed(peer)
                server.rt.say("web", "web.log.refused", peer=peer, count=count)
                self._json(403, {"error": "bad_token"})
                return
            server.attempts.passed(peer)
            self._welcome(peer)
            self._json(200, {"ok": True},
                       headers=[("Set-Cookie", self._cookie_for(presented))])

        def _refuse(self, query: dict) -> None:
            """A request with no valid token: count it, and shut the peer out if it keeps
            coming. 429 rather than 401 once locked, so the page stops re-asking."""
            peer = self._peer()
            left = server.attempts.locked(peer)
            if left > 0:
                self._json(429, {"error": "too_many", "retry_after": int(left)},
                           headers=[("Retry-After", str(int(left)))])
                return
            # A browser that simply has no cookie yet is not an attempt — only a token
            # that was PRESENTED and wrong is.
            if self._presented(query):
                count = server.attempts.failed(peer)
                server.rt.say("web", "web.log.refused", peer=peer, count=count)
            self._json(401, {"error": "unauthorised"})

        def _welcome(self, peer: str) -> None:
            """Say, once per address per run, that somebody signed in.

            The point is not bookkeeping: it is that a person watching the log — in the
            window or on their own phone — sees an address they do not recognise the
            moment it happens, rather than never.
            """
            if peer in server._seen:
                return
            server._seen.add(peer)
            server.rt.say("web", "web.log.signed_in", peer=peer)

        def _cookie_for(self, token: str) -> str:
            """The sign-in cookie: bounded, and `Secure` when the request came by HTTPS.

            `Secure` when the connection really is TLS — a certificate named on the tab,
            or something in front that says `X-Forwarded-Proto`. A phone on the home
            network over plain HTTP must NOT get it, or it could never sign in at all.
            """
            https = (self.headers.get("X-Forwarded-Proto", "").lower() == "https"
                     or isinstance(self.connection, ssl.SSLSocket))
            bits = [f"{COOKIE}={token}", "Path=/", "SameSite=Lax", "HttpOnly",
                    f"Max-Age={COOKIE_MAX_AGE_SEC}"]
            if https:
                bits.append("Secure")
            return "; ".join(bits)

        # -- the page -------------------------------------------------------
        def _page(self, path: str, query: dict) -> None:
            """Serve one file out of `static/`. A token on the URL is remembered here.

            Landing with `?token=…` sets the cookie and redirects to the bare path, so
            the address bar (and the history behind it) does not keep the token, and a
            reload works without it.
            """
            token = _one(query.get("token"))
            if token and server.accepts(token):
                server.attempts.passed(self._peer())
                self._welcome(self._peer())
                self._send(303, b"", "text/plain", headers=[
                    ("Location", path or "/"),
                    ("Set-Cookie", self._cookie_for(token))])
                return
            name = "index.html" if path in ("", "/") else path.lstrip("/")
            root = static_dir()
            full = os.path.normpath(os.path.join(root, name))
            if not full.startswith(root) or not os.path.isfile(full):
                self._send(404, b"", "text/plain")
                return
            try:
                with open(full, "rb") as fh:
                    blob = fh.read()
            except OSError:
                self._send(404, b"", "text/plain")
                return
            kind = mimetypes.guess_type(full)[0] or "application/octet-stream"
            self._send(200, blob, kind,
                       headers=[("Cache-Control", "no-cache")])

        # -- plumbing -------------------------------------------------------
        def _authorised(self, query: dict) -> bool:
            for presented in self._offered(query):
                if server.accepts(presented):
                    return True
            return False

        def _offered(self, query: dict) -> tuple:
            return (self.headers.get("X-Panel-Token", ""),
                    _cookie(self.headers.get("Cookie", "")),
                    _one(query.get("token")))

        def _presented(self, query: dict) -> bool:
            """Did this request carry a token at all? (A wrong one counts; none does not.)"""
            return any(bool(x) for x in self._offered(query))

        def _body(self) -> dict:
            try:
                length = int(self.headers.get("Content-Length") or 0)
            except ValueError:
                return {}
            if length <= 0 or length > MAX_BODY:
                return {}
            try:
                raw = self.rfile.read(length)
                data = json.loads(raw.decode("utf-8"))
            except Exception:                   # noqa: BLE001 — a bad body is an empty one
                return {}
            return data if isinstance(data, dict) else {}

        def _json(self, status: int, payload: dict, headers=None) -> None:
            blob = json.dumps(payload, ensure_ascii=False).encode("utf-8")
            self._send(status, blob, "application/json; charset=utf-8", headers)

        def _send(self, status: int, blob: bytes, kind: str, headers=None) -> None:
            try:
                self.send_response(status)
                self.send_header("Content-Type", kind)
                self.send_header("Content-Length", str(len(blob)))
                for key, value in headers or ():
                    self.send_header(key, value)
                self.end_headers()
                if blob:
                    self.wfile.write(blob)
            except (BrokenPipeError, ConnectionResetError):
                pass                            # the phone walked out of range

        def log_message(self, fmt: str, *args) -> None:
            """Into the WINDOW's debug log, never onto a console that may not exist.

            The default writes to stderr, and a windowed build (`pythonw`) has none —
            which on Windows is not "no output" but an exception on the first request.

            The window's, not this runtime's (#1306). There is one server per process
            and it answers for every open profile, but `server.rt` is whichever profile
            happened to switch it on — so `GET /api/state?profile=default` was being
            written into ANOTHER account's `debug.log`, where the person reading that
            file has no way to tell it is not theirs. `panel/debug_log.py::panel_logger`
            is the file that belongs to the window instead.
            """
            try:
                debug_log.panel_logger("web").debug(fmt, *args)
            except Exception:                   # noqa: BLE001 — logging, never the server
                pass

    return Handler


def _split(raw: str) -> tuple:
    """``(path, query)`` — the query FLATTENED to one value per name.

    `parse_qs` hands back a list per name, and every reader downstream wants the value:
    `since=[「12」]` read as a number is not 12, it is the fallback, silently — which is a
    log that re-sends its whole tail on every poll and nobody the wiser.
    """
    parsed = urllib.parse.urlsplit(raw)
    return parsed.path, {key: values[0] if values else ""
                         for key, values in urllib.parse.parse_qs(parsed.query).items()}


def _one(value) -> str:
    """One query parameter, whether it arrived as a list or already flattened."""
    if isinstance(value, (list, tuple)):
        return str(value[0]) if value else ""
    return str(value or "")


def _cookie(header: str) -> str:
    for part in (header or "").split(";"):
        key, _, value = part.strip().partition("=")
        if key == COOKIE:
            return value
    return ""
